project/pybo_project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.class_list, name='class_list')
]

project/pybo_project/pybo/urls.py
from django.urls import path
from .views import base_views
from .views import class_views
from .views import student_views

app_name = 'pybo'

urlpatterns = [
    path('', base_views.greet),
    path('suyeon_class_list/', base_views.class_list, name = 'class_list'),
    path('suyeon_class_list/<int:class_id>/', base_views.class_detail, name = 'class_detail'),
    path('suyeon_class_list/class/register/', class_views.class_register, name='class_register'),
    path('suyeon_class_list/class/modify/<int:class_id>/', class_views.class_modify, name='class_modify'),
    path('suyeon_class_list/class/delete/<int:class_id>/', class_views.class_delete, name='class_delete'),
    path('suyeon_class_list/student/register/<int:class_id>/', student_views.student_register, name='student_register'),
    path('suyeon_class_list/student/modify/<int:student_id>/', student_views.student_modify, name='student_modify'),
    path('suyeon_class_list/student/delete/<int:student_id>', student_views.student_delete, name='student_delete'),
]

project/pybo_project/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

class Class(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    class_info = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Student(models.Model):
    # 모델의 속성 값을 주의해서 작성하자...
    _class = models.ForeignKey(Class, on_delete=models.CASCADE)
    student_code = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

project/pybo_project/pybo/forms.py
from django import forms
from pybo.models import Class, Student

class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['subject', 'class_info']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'class_info': forms.Textarea(attrs={'class': 'form-control', 'rows':10}),
        }
        labels = {
            'subject' : "강의명", 
            'class_info' : '강의 정보',
        }

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['student_code']
        widgets = {
            'student_code' : forms.TextInput(attrs={'class': 'form-control', 'rows': 2})
        }
        labels = {
            'student_code': '학생 학번',
        }

project/pybo_project/pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from pybo.models import Class

def greet(request):
    return HttpResponse("곧 게시판으로 바뀌게 될거에여")

def class_list(request):
    page = request.GET.get('page', '1')
    class_list = Class.objects.order_by('-create_date')
    paginator = Paginator(class_list, 4)
    page_obj = paginator.get_page(page)
    context = {'class_list' : page_obj}
    return render(request, 'pybo/class_list.html', context)


def class_detail(request, class_id):
    _class = get_object_or_404(Class, id=class_id)
    context = { 'class': _class }
    return render(request, 'pybo/class_detail.html', context)

project/pybo_project/pybo/views/class_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages

from pybo.models import Class
from pybo.forms import ClassForm


@login_required(login_url='common:login')
def class_register(request):
    # 등록 버튼을 눌렀을 때에는 POST 방식으로 호출된다.
    if request.method == "POST":
        form = ClassForm(request.POST)
        if form.is_valid():
            _class = form.save(commit=False)
            # 글쓴이 항목 추가
            _class.professor = request.user
            _class.create_date = timezone.now()
            _class.save()
            return redirect('pybo:class_list')
    else:
        form = ClassForm()
    context = {'form' : form}
    return render(request, 'pybo/class_register_form.html', context)


@login_required(login_url='common:login')
def class_modify(request, class_id):
    _class = get_object_or_404(Class, pk=class_id)
    if request.user != _class.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:class_detail', class_id = _class.id)
    if request.method == "POST":
        form = ClassForm(request.POST, instance = _class)
        if form.is_valid():
            _class = form.save(commit=False)
            _class.modify_date = timezone.now()
            _class.save()
            return redirect('pybo:class_detail', class_id = _class.id)
        
    # 수정 버튼을 눌렀을 떄 GET 방식으로 호출된다.
    else:
        form = ClassForm(instance=_class)
    context = {'form' : form}
    return render(request, 'pybo/class_register_form.html', context)


@login_required(login_url='common:login')
def class_delete(request, class_id):
    _class = get_object_or_404(Class, pk=class_id)
    if request.user != _class.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:class_detail', class_id=_class.id)
    _class.delete()
    return redirect('pybo:class_list')
    

project/pybo_project/pybo/views/student_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages
from pybo.models import Class, Student
from pybo.forms import StudentForm

from django.contrib.auth.decorators import login_required


def student_register(request, class_id):
    _class = get_object_or_404(Class, pk=class_id)
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            student.create_date = timezone.now()
            student._class = _class
            student.save()
            return redirect('pybo:class_detail', class_id = _class.id)
    else:
        form = StudentForm()
    context = {'class' : _class, 'form':form}
    return render(request, 'pybo/student_register_form.html', context)

@login_required(login_url='common:login')
def student_modify(request, student_id):
    student = get_object_or_404(Student, pk = student_id)

    if request.user != student._class.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:class_detail', class_id = student._class.id)
    if request.method == "POST":
        form = StudentForm(request.POST, instance = student)
        if form.is_valid():
            student = form.save(commit=False)
            student.modify_date = timezone.now()
            student.save()
            return redirect('pybo:class_detail', class_id = student._class.id)
    else:
        form = StudentForm(instance = student)
    context = {'student' : student, 'form' : form}
    # 질문과는 다르게 폼을 새로 생성해줌.
    return render(request, 'pybo/student_register_form.html', context)

@login_required(login_url='common:login')
def student_delete(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    if request.user != student._class.author:
        messages.error(request, "수정권한이 없습니다.")
    else:
        student.delete()
    return redirect('pybo:class_detail', class_id = student._class.id)

project/pybo_project/templates/pybo/class_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <!-- message 표시-->
    {% if messages %}
    <div class='alert alert-danger my-3' role='alert'>
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}

    <!-- 강의 정보 -->
    <h2 class="border-bottom py-2">{{ class.subject }}</h2>
    <div class="card my-3 text-center">
        <div class = "card-header">
            작성자 : {{ class.author.username }}
        </div>

        <div class="card-body">
            <div class="card-text mb-1" style="white-space: pre-space;">{{ class.class_info }}</div>
            {% if request.user == class.author %}
            <div class="d-grid gap-2 col-2 mx-auto">
                <!--button 클래스로는 url 연결이 안된다..?-->
                <!-- 수정 -->
                <a href="{% url 'pybo:class_modify' class.id %}" class="btn btn-warning">수정</a>
                <!-- 삭제 class 값에 delete 넣어 줬어야!!!-->
                <a href="javascript:void(0)" class="delete btn btn-danger" data-uri="{% url 'pybo:class_delete' class.id %}">삭제</a>
            </div>
            {% endif %}
            
        </div>
        <div class="card-footer text-muted">
            {{ class.create_date }}
        </div>
    </div>

    <!-- 수강 학생 -->
    <h4 class="border-bottom my-3 py-2">{{ class.student_set.count }}명의 학생이 해당수업을 듣고 있습니다.</h4>
    {% for student in class.student_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line; ">{{ student.student_code }}</div>
            <div class="row">
                <div class="d-flex justify-content-end">
                    <div class="badge bg-light text-dark p-2">
                        {{ student.create_date }}
                    </div>
                </div>
                
                <div class="d-flex justify-content-end my-3">
                    {% if request.user == class.author %}
                    <!-- 수정 -->
                    <a href="{% url 'pybo:student_modify' student.id %}" class="btn btn-sm btn-outline-warning">수정</a>
                    <!-- 삭제 -->
                    <a href='#' data-uri="{% url 'pybo:student_delete' student.id %}" class="delete btn btn-sm btn-outline-danger">삭제</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if student.modify_date %}
        <div class="card-footer text-muted">
            modified at {{ student.modify_date }}
        </div>
        {% endif %}
    </div>

    {% endfor %}

    <!--답변 등록-->
    <!-- 답변 버튼 만들어서 답변 폼으로 접근하게 하기-->
    <a href="{% url 'pybo:student_register' class.id %}" method="post" class="btn btn-primary my-3">학생등록</a>

</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element)
    {
        element.addEventListener('click', function()
        {
            if(confirm("정말로 삭제하시겠습니까?"))
            {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

project/pybo_project/templates/pybo/class_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center table-primary">
            <th>번호</th>
            <th style="width:50%">강의명</th>
            <th>관리자</th>
            <th>등록일시</th>
        </tr>
        </thead>
        <tbody>
            {% if class_list %}
            {% for class in class_list %}
            <tr class="text-center">
                {% comment %} <td>{{ forloop.counter }}</td> {% endcomment %}
                <td>
                    {{ class_list.paginator.count|sub:class_list.start_index|sub:forloop.counter|add:1 }}
                </td>
                <td class="text-start">
                    {% comment %} <li><a href="/pybo/suyeon_class_list/{{ class.id }}/">{{ class.subject }}</a></li> {% endcomment %}
                    <a href="{% url 'pybo:class_detail' class.id %}"> {{ class.subject }}</a>
                    {% if class.student_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ class.student_set.count }}</span>
                    {% endif %}
                </td>
                <!-- 교수명 추가 -->
                <td>{{ class.author.username }}</td>
                <td> {{ class.create_date }} </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">강의가 존재하지 않습니다.</td>
            </tr>

            {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 -->

    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if class_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ class_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex = "-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        <!--넘버링 페이지-->
        {% for page_number in class_list.paginator.page_range %}
        {% if page_number >= class_list.number|add:-2 and page_number <= class_list.number|add:2 %}
        {% if page_number == class_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if class_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ class_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <a href="{% url 'pybo:class_register' %}" class="btn btn-primary">강의 등록하기</a>
</div>
{% endblock %}

project/pybo_project/templates/pybo/class_register_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">강의 등록</h5>
    <form method="post">
        {% csrf_token %}
        <!--오류표시-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.erros }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

project/pybo_project/templates/pybo/student_form.html
<!-- 학번 수정하는 폼을 새로 생성하게 되면 자동으로 탭 처리가 되어버린다. -->
<!-- 따라서 애초에 학생등록 폼을 만드는 것을 선택했다.-->
{% extends 'base.html' %}
{% block content %}

<!-- 학번 수정 -->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <h3 class="border-bottom my-3 py-2">수정 답변 내용 </h3>

            <textarea class="form-control" name="student_code" id="student_code" rows="2">
                {{ form.student_code.value|default_if_none:'' }}
            </textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

project/pybo_project/templates/pybo/student_register_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h5 class="my-3 border-bottom pb-2">학생 등록</h5>
    <form method="post">
        {% csrf_token %}
        <!--오류표시-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.erros }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}