project/pybo_project/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name ='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name="signup"),
]

project/pybo_project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.class_list, name='class_list')
]

project/pybo_project/pybo/urls.py
from django.urls import path
from .views import base_views
from .views import class_views
from .views import student_views

app_name = 'pybo'

urlpatterns = [
    path('', base_views.greet),
    path('suyeon_class_list/', base_views.class_list, name = 'class_list'),
    path('suyeon_class_list/<int:class_id>/', base_views.class_detail, name = 'class_detail'),
    path('suyeon_class_list/class/register/', class_views.class_register, name='class_register'),
    path('suyeon_class_list/class/modify/<int:class_id>/', class_views.class_modify, name='class_modify'),
    path('suyeon_class_list/class/delete/<int:class_id>/', class_views.class_delete, name='class_delete'),
    path('suyeon_class_list/student/register/<int:class_id>/', student_views.student_register, name='student_register'),
    path('suyeon_class_list/student/modify/<int:student_id>/', student_views.student_modify, name='student_modify'),
    path('suyeon_class_list/student/delete/<int:student_id>', student_views.student_delete, name='student_delete'),
]

project/pybo_project/pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from pybo.models import Class

def greet(request):
    return HttpResponse("곧 게시판으로 바뀌게 될거에여")

def class_list(request):
    page = request.GET.get('page', '1')
    class_list = Class.objects.order_by('-create_date')
    paginator = Paginator(class_list, 4)
    page_obj = paginator.get_page(page)
    context = {'class_list' : page_obj}
    return render(request, 'pybo/class_list.html', context)


def class_detail(request, class_id):
    _class = get_object_or_404(Class, id=class_id)
    context = { 'class': _class }
    return render(request, 'pybo/class_detail.html', context)

project/pybo_project/templates/base.html
{% load static %}
<!doctype html>

<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!--bootstrap css zone-->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        
        <title>Suyeon's Pybo</title>
    </head>
    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
        <!-- Bootstrap JS zone -->
        <script src="{% static 'bootstrap.min.js' %}"></script>

        <!--자바 스크립트-->
        {% block script %}
        {% endblock %}

    </body>
</html>

project/pybo_project/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
        {% endfor %}
    </div>
{% endif %}

project/pybo_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:class_list' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}"> {{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
    